version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tiffincrm-server
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 200
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

